### ISSUE TITLE
PUT /user/:userId

### ISSUE THREAD

**Issue by seriousManual** [hackerspace-bootstrap/strichliste#11]

**Comment by seriousManual** [comment]
as of now, the endpoint has to support:

* renaming (changing the name)
* set pin protection
* remove pin protection
* set/change email adress

the endpoint has to query for the pin if one is set (as with any other operation a pin protected user is doing)

**Comment by schinken** [comment]
Moved to strichliste2: https://github.com/strichliste/server/issues/2
