### ISSUE TITLE
I would love to be able to have a get method to search by username instead of userID

### ISSUE THREAD

**Issue by ashg1990** [hackerspace-bootstrap/strichliste#118]
This api call could really be worth adding would help many i need to often search by usename but have to create other scripts to handle all the data then parse the data out by username.
Would just love a call like 0.0.0.0/user/userName/

**Comment by schinken** [comment]
I would say it's bad to have the same resource available under different URIs. Maybe a search route would be nice which returns users by different filters (username, email, ...)

**Comment by ashg1990** [comment]
yes that would be nice but have no knowledge on how to go about this :/

**Comment by schinken** [comment]
This has been addressed in strichliste2, which is currently under development (https://github.com/strichliste/server/commit/04de129c0d430440f269280ea3004fab67227e7c)
