### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by thelegy** [hackerspace-bootstrap/strichliste#270]
Hi everyone.

We are using two instances of strichliste all the time and for events (usually a few days multiple times a year) we spin up another instance.

To make our workflow as easy as possible we use docker containers. For the better part of the last two years we built the containers in our own gitlab instance and pushed it to our internal docker registry.

If you are interested in docker containers for strichliste i would offer to add a PR with the Dockerfile to build a slim container containing the api.

I was asked to publish the container by someone from a different university so i believe the demand is present.

**Comment by schinken** [comment]
Hi there!

Of course you can provide a dockerfile. I'm currently working on strichliste2 and I would need your help with docker there, too, if you're interested (https://github.com/strichliste/)

Is it okay to *ping* you, if we're "ready"? ;)
