### ISSUE TITLE
Add option to disable users

### ISSUE THREAD

**Issue by NicoHood** [hackerspace-bootstrap/strichliste#272]
I sometimes misstyped a username or wanted to remove a user. I know that this feature should not be available in the frontend, as trolls could delete user accounts.

I can alter the sqlite database manually and remove users, however this will break the transactions table (it has entries with user ids that should not exist). So the best (and i guess a common way) is to disable a user and keep the history. Why not use the active flag for this:
* 1 = active
* 0 = inactive
* -1 = disabled

This way the database history is kept for disabled users, but they will not be shown in the gui anymore. This feature can get combined with #39 .

As a side note: When I delete a user which also exists in the transactions table there is no error shown. Normally sql should forbit to delete the user. I guess that is because the userId was not selected as foreign key. Should I open a new bug for this? I guess this is technically wrong.

**Comment by schinken** [comment]
Added this to strichliste2: https://github.com/strichliste/server/issues/2

I guess only active and inactive is useful. Inactive is the same as disabled in my opinion. Inactive in your sense if maybe "Last transaction older than 14 days"
