### ISSUE TITLE
Undo last transaction

### ISSUE THREAD

**Issue by foosinn** [hackerspace-bootstrap/strichliste#280]
Support for undoing or changing  the last transaction would be nice.

Thanks!

**Comment by schinken** [comment]
Good point! I'm going to transfer that to strichliste#2. Maybe just with a "grace period" like "only the last x min"?

**Comment by foosinn** [comment]
I guess, around one to five minutes should be fine.

**Comment by schinken** [comment]
Moved to https://github.com/strichliste/strichliste/issues/27
