### ISSUE TITLE
Pin protection

### ISSUE THREAD

**Issue by schinken** [hackerspace-bootstrap/strichliste#3]
Make it possible to protect a user by pin/password/callItWhatYouWant

**Comment by schinken** [comment]
I've talked to some people with the result, that we should go with https as transport security. Pins should be stored hashed and salted into the database (add two more fields to the user table)

Maybe deny access to pin-protected /user endpoint if protocol is not https

**Comment by seriousManual** [comment]
Proposal:
As the frontend does not know if a pin is necessary when submitting a transaction, the api could communicate that fact by answering with 401 (if no pin has been submitted) causing the frontend to query the user for a pin and resubmit the transaction.

**Comment by seriousManual** [comment]
is the pin obligatory for every user?
what about making it opt-in so that the user has the choice to set a pin when the user is created.

**Comment by seriousManual** [comment]
the protocol must be ssl

**Comment by seriousManual** [comment]
the pin is transmitted either via basic-auth or an custom header of sorts

**Comment by schinken** [comment]
Add config parameter to enable/disable this feature and provide this on the `/settings` endpoint

**Comment by schinken** [comment]
Moved to strichliste2: https://github.com/strichliste/server/issues/1
