### ISSUE TITLE
Add product database

### ISSUE THREAD

**Issue by schinken** [hackerspace-bootstrap/strichliste#38]
Add possibility to store EAN Codes, Product Names and Price

POST /user/:userId/transaction should also support { eanCode: "....." }

**Comment by seriousManual** [comment]
in essence this means it should be possible to enrich a transaction with (arbitrary) meta data?

**Comment by schinken** [comment]
I think for the first step, it would be nice to have a "product" table, and an API-endpoint where you can issue a transaction by EAN number and/or product id. 

Internally the price is grabbed from the product table and a transaction (just the value) is inserted.

Maybe a product reference could be added to the transaction-table which is NULL by default - what do you think?

**Comment by seriousManual** [comment]
this somehow interferes/collides with the plan of adding an articleId at the transaction level.
should this be tackled individually?

**Comment by schinken** [comment]
The transaction table needs a articleId reference, which can be NULL if it's a normal money-transaction. I will submit a proposal for the article database. We can defer the ADD COLUMN articleId as long as there is no article table, or just add it right away... 

:)

**Comment by schinken** [comment]
Fixed here: https://github.com/strichliste/server/commit/caaac989d47cadc908982064ab5ea59df3150c2c
