### ISSUE TITLE
Can't submit another transaction if one limit exceeded

### ISSUE THREAD

**Issue by schinken** [hackerspace-bootstrap/strichliste#41]
The problem lies within this check for boundaries:
https://github.com/hackerspace-bootstrap/strichliste/blob/master/lib/routes/UserIdTransaction.post.js#L40

If I exceeded for some reason one boundary (e.g. due to a config change), one can't make  transactions anymore.

Example:
userBalance: -42
boundary: -41

Now I want to pay my debt -> boundaries exceeded

**Comment by else** [comment]
"debt"

**Comment by schinken** [comment]
Unit tests still needed!
