### ISSUE TITLE
Add API call to query transactions per user per day

### ISSUE THREAD

**Issue by breti** [hackerspace-bootstrap/strichliste#42]
We want to implement a script which sends a mail per user with all transactions of the past day. Unfortunately there's no API call to filter the transactions per date, so I'd have to query all transactions and filter the result in the script.

An API call which returns a structure with all users and their transactions of the date specified would be very handy to simplify this. Users with no transactions should be hidden in this result.

Of course the local timezone should be considered.

**Comment by schinken** [comment]
That's basically what #37 is about. Arguments like the dateRange should be provided

**Comment by seriousManual** [comment]
what about closing this issue and adding the dayParameter in #37 ?

**Comment by schinken** [comment]
That's basically what I said in my comment before ;)
I think we should provide something like dateBegin and dateEnd.

**Comment by schinken** [comment]
Moved to strichliste2: https://github.com/strichliste/server/issues/3
