### ISSUE TITLE
Configurable database backend

### ISSUE THREAD

**Issue by schinken** [hackerspace-bootstrap/strichliste#44]
Maybe it would be nice to have other database backends and introduce a query builder like squel.js with this step. 

The reason is: I think it would be nice that one can use mysql if there's already a running instance, because multiple applications an query the database - not just one using the sqlite database

**Comment by seriousManual** [comment]
sounds like a good idea, needs some refactoring though.

**Comment by schinken** [comment]
Strichliste2 automatically provides that functionality out of the box (because of doctrine) https://github.com/strichliste/server

See: https://www.doctrine-project.org/projects/doctrine-dbal/en/2.8/reference/platforms.html
