### ISSUE TITLE
Add the possibility to transfer money from one user to the other

### ISSUE THREAD

**Issue by seriousManual** [hackerspace-bootstrap/strichliste#80]
Proposal:

POST /transfer

```
{
  fromUserId: 123,
  toUserId: 42,
  value: 32
}
```

as a result the api will create two transactions, one that charges the 'fromUserId' user, and one that adds the funding to the 'toUserId' user.

**Comment by schinken** [comment]
:+1:

**Comment by seriousManual** [comment]
actually this interface would be better:

POST /user/<fromUserId>/transaction

````
{
  toUserId: 45,
  value: 123
}
````

this way we`d get pin authentication for free (when implemented on the user level)

**Comment by schinken** [comment]
You're right! Let's go with this

**Comment by NicoHood** [comment]
Any progress on this one? We solved it by hacking the (selfmade) frontend with adding two transactions for sending money.
