### ISSUE TITLE
Floating points are unsuitable for currency values

### ISSUE THREAD

**Issue by Don42** [hackerspace-bootstrap/strichliste#95]
Since floating point values are not always 100% accurate it is
preferable to use integer values of the smallest currency value (cents).

This would probably be a large change, since changes need to be done at
every level of the application (Database, Backend, Frontend).

**Comment by else** [comment]
I would once more support this request, although my previous one was dismissed. A patch probably helps.

**Comment by schinken** [comment]
We're planning to chance the layout to store cents. This is a breaking change, but I'm sure we'll do it

**Comment by else** [comment]
:+1

**Comment by Don42** [comment]
It might be easiest to implement a new versioned API that uses integers and have a transition period during which the old version still exists.
For example:
`/v2/user`
`/v2/user/*/transaction`

That way, future API changes are easier to implement.

**Comment by seriousManual** [comment]
i don't see this as a breaking or backwards incompatible change.
when the way a value is stored in the database is changed this does not neccessarily have any impact on other components like the frontend.

**Comment by schinken** [comment]
@seriousManual Maybe we don't want to send the values as float in the json response anymore. Maybe we can use a string?

**Comment by Don42** [comment]
@schinken I am using integers in the database and the json requests and responses. That way it's the same representation everywhere.

https://github.com/Don42/strichliste-python/blob/master/endpoints/v2/user.py#L94

**Comment by schinken** [comment]
Fixed in strichliste2
